name: 'futuremind_movies'
version: '1.0.0'

profile: 'futuremind_movies'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  futuremind_movies:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    marts:
      +materialized: table